---
driver:
  name: vagrant
  name: digitalocean

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: vagrant
  - name: centos-6.4
    driver:
      name: vagrant
  - name: digitalocean-ubuntu-10.04
    driver:
      name: digitalocean
      image: ubuntu-10-04-x32
      access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  - name: digitalocean-ubuntu-12.04
    driver:
      name: digitalocean
      image: ubuntu-12-04-x32
      access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  - name: digitalocean-centos-5.8
    driver:
       name: digitalocean
       image: centos-5-8-x32
       access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
       ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  - name: digitalocean-centos-6.5
    driver:
       name: digitalocean
       image: centos-6-5-x32
       access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
       ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
# suite names taken from https://www.ruby-lang.org/en/downloads/
  - name: current_stable
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.2.1"} }
  - name: previous_stable
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.1.5"}}
  - name: old_stable_200_series
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.0.0-p643"}}
  - name: old_stable_193_series
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "1.9.3-p551"}}
  - name: ruby-2.0.0-p247
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.0.0-p247"}}
