---
driver:
  name: vagrant
  name: digitalocean

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: vagrant
  - name: centos-6.4
    driver:
      name: vagrant
  - name: digitalocean-ubuntu-10.04
    driver:
      name: digitalocean
      image: ubuntu-10-04-x32
      access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  - name: digitalocean-centos-5.8
    driver:
       name: digitalocean
       image: centos-5-8-x32
       access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
       ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
  - name: default
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "1.9.2-p320"}}
  - name: ruby-2.0
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.0.0-p598"}}
  - name: ruby-1.8
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "1.8.7-p374"}}