---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: vagrant
  - name: centos-6.4
    driver:
      name: vagrant

suites:
  - name: default
    run_list:
      - recipe[ruby::default]
      - recipe[ruby::rubygems]
    attributes: {ruby: {version: "1.9.2-p320"}}
  - name: ruby-2.0
    run_list:
      - recipe[ruby::default]
      - recipe[ruby::rubygems]
    attributes: {ruby: {version: "2.0.0-p598"}}
  - name: ruby-1.8
    run_list:
      - recipe[ruby::default]
      - recipe[ruby::rubygems]
    attributes: {ruby: {version: "1.8.7-p374"}}