---
driver:
  name: digitalocean

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

provisioner:
  name: chef_solo

platforms:
  - name: digitalocean-ubuntu-10.04
    driver:
      name: digitalocean
      image: ubuntu-10-04-x32
      access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
  - name: default
    run_list:
      - recipe[ruby::default]
      - recipe[ruby::rubygems]
    attributes: {ruby: {version: "1.9.2-p320"}}
