---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      name: vagrant
      box: ubuntu/trusty64
  - name: centos-7.0
    driver:
      name: vagrant
      box: centos/7
suites:
# suite names taken from https://www.ruby-lang.org/en/downloads/
  - name: current_stable
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.4.0"} }
  - name: previous_stable
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.3.3"}}
  - name: old_stable
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::rubygems]
    attributes: {ruby: {version: "2.2.6"}}
  - name: uninstall
    run_list:
      - recipe[chef-ruby::default]
      - recipe[chef-ruby::uninstall]
    attributes: {ruby: {version: "2.3.3"}, {uninstall: {version: "2.3.3"}}}



