language: ruby

rvm:
  - 2.0.0

bundler_args: --jobs 7 --without kitchen_vagrant --without development

branches:
  only:
    - master

before_install:
- git clone https://github.com/opscode-cookbooks/apt.git $TRAVIS_BUILD_DIR/apt
- git clone https://github.com/opscode-cookbooks/build-essential.git $TRAVIS_BUILD_DIR/build-essential
- git clone https://github.com/opscode-cookbooks/yum.git $TRAVIS_BUILD_DIR/yum
- git clone https://github.com/opscode-cookbooks/yum-epel.git $TRAVIS_BUILD_DIR/yum-epel
- bundle install

script: bundle exec rake travis:ci

after_script:
- bundle exec kitchen destroy
